### ISSUE TITLE
Приемы разметки...

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#11]
Не совсем хороший подход, обычно так не делают
https://github.com/kirillstepanchuk/tehnomart/blob/4bcb3b7331cc1aeab9a8a1a4c40112f2646b10e1/index.html#L237-L238

В данной фразе логически всего один параграф, т.е. (по сути) одно предложение. 
Размечать подобные фрагменты лучше примерно так:
```
<p class="...">
     <span class="...">Обратная связь:</span>
     <a class="..." href="mailto:mail@htmlacademy.ru">mail@htmlacademy.ru</a>
</p>
```

Еще раз пройдись по блочно-строчной модели - в данном случае span и ссылка прекрасно уживаются внутри параграфа

**Comment by kirillstepanchuk** [comment]
все сделал в соответствии
