### ISSUE TITLE
Нарушения критериев

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#12]
Множественные нарушения критерия Б15
http://joxi.ru/ZrJlP8YTMkXnj2

**Comment by Morfey216** [comment]
Несоответствие макету
https://github.com/kirillstepanchuk/tehnomart/blob/4bcb3b7331cc1aeab9a8a1a4c40112f2646b10e1/index.html#L34

**Comment by kirillstepanchuk** [comment]
добавил табы, на главной нет блока регистрации и входа , тк и в каталоге и на главной пользователь авторизирован

**Comment by Morfey216** [comment]
По Б15 еще много чего осталось

**Comment by kirillstepanchuk** [comment]
проверил все отступы
