### ISSUE TITLE
Главная

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#14]
Не вижу ссылки на главную страницу
https://github.com/kirillstepanchuk/tehnomart/blob/67a896fd2857159afd7c51618443998daf501d0c/catalog.html#L71-L81

**Comment by kirillstepanchuk** [comment]
исправил

**Comment by Morfey216** [comment]
Это неправильный вариант
https://github.com/kirillstepanchuk/tehnomart/blob/92bcf8adaccace2f8db2091fe6384c970be633a1/catalog.html#L87
Как бы выглядела разметка, если бы не было иконки-домика? Вот так и надо разметить
