### ISSUE TITLE
Странности разметки...

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#17]
Можно ли как-то объяснить разницу в разметке?
Здесь:
https://github.com/kirillstepanchuk/tehnomart/blob/67a896fd2857159afd7c51618443998daf501d0c/index.html#L30-L31
И здесь:
https://github.com/kirillstepanchuk/tehnomart/blob/67a896fd2857159afd7c51618443998daf501d0c/catalog.html#L32-L33

**Comment by kirillstepanchuk** [comment]
изменил
