### ISSUE TITLE
Потенциальные проблемы с передачей данных

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#19]
Это поле нужно поместить в тег form, т.к. возникнут проблемы при отправке данных на сервер либо при обработке запроса поиска скриптами
https://github.com/kirillstepanchuk/tehnomart/blob/204401c4ef616eb8d29fbb2f57329c6173682fc0/index.html#L16

**Comment by kirillstepanchuk** [comment]
поместил

**Comment by Morfey216** [comment]
А иконка почему за пределами формы?
https://github.com/kirillstepanchuk/tehnomart/blob/24ba47af2d3d5a36f0f08cf1374164d863159727/index.html#L15-L18

**Comment by kirillstepanchuk** [comment]
включил в форму
