### ISSUE TITLE
Ссылки

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#2]
Закладки, корзина, оформить заказ - это всё ссылки

https://github.com/kirillstepanchuk/tehnomart/blob/a28a5d5a3c627f389d110a08939c6744e8312468/index.html#L18-L20

Телефон - тоже ссылка.  
https://github.com/kirillstepanchuk/tehnomart/blob/a28a5d5a3c627f389d110a08939c6744e8312468/index.html#L31-L34

Посмотри примеры: https://developer.mozilla.org/ru/docs/Web/HTML/Element/A#Example
И куча лишних div-ов...

Эти элементы - тоже ссылки
https://github.com/kirillstepanchuk/tehnomart/blob/a28a5d5a3c627f389d110a08939c6744e8312468/index.html#L183
https://github.com/kirillstepanchuk/tehnomart/blob/a28a5d5a3c627f389d110a08939c6744e8312468/index.html#L209
https://github.com/kirillstepanchuk/tehnomart/blob/a28a5d5a3c627f389d110a08939c6744e8312468/index.html#L213

**Comment by Morfey216** [comment]
Остались "хвосты"
https://github.com/kirillstepanchuk/tehnomart/blob/4bcb3b7331cc1aeab9a8a1a4c40112f2646b10e1/catalog.html#L201-L202

**Comment by Morfey216** [comment]
Это тоже ссылки - так называемые "хлебные крошки" (breadcrumbs)
https://github.com/kirillstepanchuk/tehnomart/blob/4bcb3b7331cc1aeab9a8a1a4c40112f2646b10e1/catalog.html#L72

**Comment by Morfey216** [comment]
Еще не размечены ссылки
https://github.com/kirillstepanchuk/tehnomart/blob/4bcb3b7331cc1aeab9a8a1a4c40112f2646b10e1/catalog.html#L41
https://github.com/kirillstepanchuk/tehnomart/blob/4bcb3b7331cc1aeab9a8a1a4c40112f2646b10e1/catalog.html#L43

**Comment by kirillstepanchuk** [comment]
закладки , корзину , телефоны , ссылку на сайт , емайл , хлебные крошки ,картинки -все сделал ссылками

**Comment by Morfey216** [comment]
Сделать-то сделал, да с нарушением пункта 3.4 ТЗ

**Comment by kirillstepanchuk** [comment]
сделал имя пользователя ссылкой

**Comment by Morfey216** [comment]
Это должна быть одна ссылка, а не две, внимательнее читай ТЗ
https://github.com/kirillstepanchuk/tehnomart/blob/92bcf8adaccace2f8db2091fe6384c970be633a1/index.html#L35-L36

**Comment by kirillstepanchuk** [comment]
сделал
