### ISSUE TITLE
Предусматриваем изменение данных

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#20]
Числовые значения в подобных случаях нужно помещать в отдельный тег, например - в span. Это позволит при помощи JS-скриптов или php установить сразу нужное значение, не вырезая ничего из текста
https://github.com/kirillstepanchuk/tehnomart/blob/204401c4ef616eb8d29fbb2f57329c6173682fc0/index.html#L19-L20

**Comment by kirillstepanchuk** [comment]
добавил числа в <span>
