### ISSUE TITLE
Ссылка без текста

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#21]
aria-label - это, конечно, хорошо. Однако в данном случае визуально вся информация будет представлено только пиктограммой - ее лучше подписать. Опять на помощь приходит span ))
https://github.com/kirillstepanchuk/tehnomart/blob/204401c4ef616eb8d29fbb2f57329c6173682fc0/index.html#L38-L39

**Comment by kirillstepanchuk** [comment]
добавил span
