### ISSUE TITLE
Снова Б15

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#22]
Множественные нарушения критерия

https://github.com/kirillstepanchuk/tehnomart/blob/204401c4ef616eb8d29fbb2f57329c6173682fc0/index.html#L42-L43

https://github.com/kirillstepanchuk/tehnomart/blob/204401c4ef616eb8d29fbb2f57329c6173682fc0/catalog.html#L107-L108

https://github.com/kirillstepanchuk/tehnomart/blob/204401c4ef616eb8d29fbb2f57329c6173682fc0/catalog.html#L120-L122

https://github.com/kirillstepanchuk/tehnomart/blob/204401c4ef616eb8d29fbb2f57329c6173682fc0/catalog.html#L133-L139

**Comment by kirillstepanchuk** [comment]
исправил

**Comment by Morfey216** [comment]
Не исправлено
https://github.com/kirillstepanchuk/tehnomart/blob/24ba47af2d3d5a36f0f08cf1374164d863159727/catalog.html#L104-L114
https://github.com/kirillstepanchuk/tehnomart/blob/24ba47af2d3d5a36f0f08cf1374164d863159727/catalog.html#L117-L119
и так далее...

**Comment by kirillstepanchuk** [comment]
реально тупанул, исправил
