### ISSUE TITLE
Иерархия заголовков

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#24]
Доставка, Гарантия, Кредит - эти участки логически подчинены блоку Сервисы, верно? Следовательно - заголовки у них должны быть не h2
https://github.com/kirillstepanchuk/tehnomart/blob/204401c4ef616eb8d29fbb2f57329c6173682fc0/index.html#L186-L203

**Comment by kirillstepanchuk** [comment]
исправил
