### ISSUE TITLE
Блок карты

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#26]
Мне очень не нравится, как ты реализовал блок карты!
https://github.com/kirillstepanchuk/tehnomart/blob/204401c4ef616eb8d29fbb2f57329c6173682fc0/index.html#L222-L229

1. Alt - не информативен! Правильно будет - вписать сюда адрес! Т.е. если изображение не подгрузится, пользователь прочтет этот адрес в подписи
2. Изображение не кликабельно, т.е. никуда не ведет - сделать ссылкой
3. Зачем здесь добавлено изображение большого размера?

**Comment by kirillstepanchuk** [comment]
выполнено
