### ISSUE TITLE
CapsLock в тексте

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#27]
При наборе подобных фрагментов текста не нужно писать его прописными, пиши обычным образом. Эффект прописного текста реализуется при стилизации.
Некоторые примеры в разметке:
https://github.com/kirillstepanchuk/tehnomart/blob/204401c4ef616eb8d29fbb2f57329c6173682fc0/index.html#L200
https://github.com/kirillstepanchuk/tehnomart/blob/204401c4ef616eb8d29fbb2f57329c6173682fc0/index.html#L220
https://github.com/kirillstepanchuk/tehnomart/blob/204401c4ef616eb8d29fbb2f57329c6173682fc0/index.html#L246
Нужно пройтись по всему коду и исправить

**Comment by kirillstepanchuk** [comment]
исправил

**Comment by Morfey216** [comment]
Ну ты же в обычной жизни так не пишешь:
https://github.com/kirillstepanchuk/tehnomart/blob/24ba47af2d3d5a36f0f08cf1374164d863159727/index.html#L160
https://github.com/kirillstepanchuk/tehnomart/blob/24ba47af2d3d5a36f0f08cf1374164d863159727/index.html#L179
https://github.com/kirillstepanchuk/tehnomart/blob/24ba47af2d3d5a36f0f08cf1374164d863159727/index.html#L193

Ты пишешь "Сервисы" "Доставка" и т.д. Вот так и пиши )
Без кавычек, естественно )

**Comment by kirillstepanchuk** [comment]
ну вообще в обычной жизни так за меня пишет телефон )) ну это я понял , изменил
