### ISSUE TITLE
Форма

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#28]
Не наблюдаю формы в этом коде...
https://github.com/kirillstepanchuk/tehnomart/blob/204401c4ef616eb8d29fbb2f57329c6173682fc0/index.html#L235-L247

**Comment by Morfey216** [comment]
У блока фильтрации на странице каталога также отсутствует форма!!!

**Comment by kirillstepanchuk** [comment]
исправил

**Comment by Morfey216** [comment]
Заголовок h2 я бы вынес перед формой
https://github.com/kirillstepanchuk/tehnomart/blob/24ba47af2d3d5a36f0f08cf1374164d863159727/catalog.html#L99-L102

**Comment by kirillstepanchuk** [comment]
вынес
