### ISSUE TITLE
Отсутствие модального окна

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#29]
Не вижу в разметке модального окна карты.
Модальное окно добавления товара в корзину тоже отсутствует.

**Comment by kirillstepanchuk** [comment]
все добавил

**Comment by Morfey216** [comment]
Всё, да не всё: на главной тоже есть карточки товара, и, значит, его (товар) тоже можно добавить в корзину, а модального окна я не увидел

**Comment by kirillstepanchuk** [comment]
понял, исправил
