### ISSUE TITLE
Заголовок

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#3]
Здесь не параграф! Это заголовок первого уровня.
И зачем тебе здесь div? Вообще, по всему коду слишком много лишних оберток, их нужно убрать

https://github.com/kirillstepanchuk/tehnomart/blob/a28a5d5a3c627f389d110a08939c6744e8312468/index.html#L24-L30

Это заголовки

https://github.com/kirillstepanchuk/tehnomart/blob/a28a5d5a3c627f389d110a08939c6744e8312468/index.html#L79
https://github.com/kirillstepanchuk/tehnomart/blob/a28a5d5a3c627f389d110a08939c6744e8312468/index.html#L94

**Comment by Morfey216** [comment]
не исправлено:
https://github.com/kirillstepanchuk/tehnomart/blob/4bcb3b7331cc1aeab9a8a1a4c40112f2646b10e1/catalog.html#L77
https://github.com/kirillstepanchuk/tehnomart/blob/4bcb3b7331cc1aeab9a8a1a4c40112f2646b10e1/catalog.html#L80

**Comment by kirillstepanchuk** [comment]
заменил на заголовок первого уровня , во втором случае второго уровня
