### ISSUE TITLE
Отдельный блок кода

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#31]
Направление сортировки имеет смысл выделить в отдельный участок, т.е. отделить от видов сортировки (По цене, По типу, По функционалу), т.к. назначение этих элементов совсем другое
https://github.com/kirillstepanchuk/tehnomart/blob/204401c4ef616eb8d29fbb2f57329c6173682fc0/catalog.html#L99-L100

И еще, попутно, - на русскоязычном сайте все подписи для посетителя нужно писать на русском языке, т.е. up-down нужно заменить на русский аналог. По коду есть еще несколько похожих моментов, например - кнопка Закрыть у модального окна

**Comment by kirillstepanchuk** [comment]
отделил , по коду прошелся и на русский исправил некоторое

**Comment by Morfey216** [comment]
Правильнее было бы "По возрастанию" и "По убыванию"
https://github.com/kirillstepanchuk/tehnomart/blob/24ba47af2d3d5a36f0f08cf1374164d863159727/catalog.html#L157-L158

**Comment by kirillstepanchuk** [comment]
исправил
