### ISSUE TITLE
Атрибуты тегов

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#33]
1. У форм отсутствует method
https://github.com/kirillstepanchuk/tehnomart/blob/24ba47af2d3d5a36f0f08cf1374164d863159727/index.html#L244
2. У всех контентных изображений должны быть прописаны размеры
https://github.com/kirillstepanchuk/tehnomart/blob/24ba47af2d3d5a36f0f08cf1374164d863159727/index.html#L265

**Comment by kirillstepanchuk** [comment]
добавил метод , размеры

**Comment by Morfey216** [comment]
> добавил метод , размеры

Серьезно? ))
https://github.com/kirillstepanchuk/tehnomart/blob/6f7a89a7947c69cdfc9fadae522f6e7eb1dadbf1/index.html#L290
Я же написал: "у всех контентных изображений"! Логотип - это контент!

**Comment by kirillstepanchuk** [comment]
исправил
