### ISSUE TITLE
Неправильно поле

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#34]
Здесь уместен textarea
https://github.com/kirillstepanchuk/tehnomart/blob/24ba47af2d3d5a36f0f08cf1374164d863159727/index.html#L254
http://htmlbook.ru/html/textarea

П.С. И почему все id-шники через filter?

**Comment by kirillstepanchuk** [comment]
добавил textarea , немного поменял айди ,  в лекции он ставил приставку filter , я с ней немного переборщил

**Comment by kirillstepanchuk** [comment]
поменял там где сообщение отправляется

**Comment by Morfey216** [comment]
> добавил textarea , немного поменял айди , в лекции он ставил приставку filter , я с ней немного переборщил

С id-шниками существует потенциальная проблема того, что случайно в разных местах можно указать два одинаковых id, что недопустимо в пределах одной страницы. Чтобы этого избежать, можно к id добавлять приставку в виде названия блока, в котором id находится. Вероятнее всего, в лекции речь шла о блоке фильтрации, поэтому был добавлен filter. 
В твоем случае уместно было бы использовать "feedback", так как речь идет о блоке обратной связи.
Т.е. feedback-user-name, feedback-message и т.д.

На странице каталога в блоке фильтрации да, уместен filter

**Comment by kirillstepanchuk** [comment]
понял , исправил
