### ISSUE TITLE
Дорабатываем формы

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#35]
1. Метод get подойдет не везде. В данном макете он хорошо подходит в форме поиска, во всех остальных случаях лучше использовать method="post"
2. Доступность.
Возьмем код формы поиска:
https://github.com/kirillstepanchuk/tehnomart/blob/6f7a89a7947c69cdfc9fadae522f6e7eb1dadbf1/index.html#L15-L18
а) img здесь точно будет лишнее, а вот label стоило бы добавить, и уже внутрь label поместить изображение. И будет это не img, но об этом чуть позже.
б) Поскольку единственной надписью является placeholder, это следует исправить, добавив информацию для "читалок". В результате поле input станет таким:

`<input type="search" name="search" id="search" aria-label="Поиск по сайту" placeholder="Поиск:">`

если посмотреть внимательно - тип поля также изменился )

3. Доработаем участок с выбором цены в форме фильтрации... Разметить ползунки можно так:

```
<div class="range">
   <div class="range__block">
     <div class="range__bar"></div>
     <button class="range__min"></button>
     <button class="range__max"></button>
  </div>
</div>
```
Ну, а поля с ценами - всё как обычно, label + input

**Comment by kirillstepanchuk** [comment]
сделал

**Comment by Morfey216** [comment]
Уверен, можно обойтись без span
https://github.com/kirillstepanchuk/tehnomart/blob/205e73d379d0c4c007973763176b3deddf901b6a/catalog.html#L118-L120
https://github.com/kirillstepanchuk/tehnomart/blob/205e73d379d0c4c007973763176b3deddf901b6a/catalog.html#L123-L125

А вот здесь его явно не хватает:
https://github.com/kirillstepanchuk/tehnomart/blob/205e73d379d0c4c007973763176b3deddf901b6a/catalog.html#L122

**Comment by Morfey216** [comment]
Двойные нижние подчеркивания можно было заменить на дефис (с целью соблюдения однотипности стиля написания кода)
https://github.com/kirillstepanchuk/tehnomart/blob/205e73d379d0c4c007973763176b3deddf901b6a/catalog.html#L111-L115

**Comment by kirillstepanchuk** [comment]
заменил

**Comment by Morfey216** [comment]
Замену подчеркивания я видел... А со span-ами почему не разобрался?

**Comment by kirillstepanchuk** [comment]
разобрался
