### ISSUE TITLE
Пресловутый Б15

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#36]
https://github.com/kirillstepanchuk/tehnomart/blob/990bbbdebe64bd24c846aeb13040ca631a64c8db/css/style.css#L4

**Comment by kirillstepanchuk** [comment]
поправил

**Comment by Morfey216** [comment]
Не исправлено! Множественные нарушения критерия Б15 - я насчитал 18 штук!
https://github.com/kirillstepanchuk/tehnomart/blob/23f56092d99752d1a10e674740ec57ef9b3c08d6/css/style.css#L5

Б15. Единообразное написание и форматирование кода в HTML, CSS и JavaScript.
Критерий рассматривает единообразие в написании кода:
• используется один тип кавычек: в одном языке (HTML, CSS или JS) должны использоваться только кавычки определённого типа (двойные или одинарные). Однако между языками тип кавычек может отличаться;
