### ISSUE TITLE
Фоновый цвет

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#37]
Для блоков, у которых есть фоновое изображение, нужно прописать фоновый цвет, примерно похожий на основной цвет изображения.
https://github.com/kirillstepanchuk/tehnomart/blob/990bbbdebe64bd24c846aeb13040ca631a64c8db/css/style.css#L130-L132

Иначе, если фоновая картинка не загрузится, то будет так:
http://joxi.ru/l2ZOPaRsEaLYjA
Белый цвет текста на белом фоне, мягко говоря, не удобно читать

**Comment by kirillstepanchuk** [comment]
добавил

**Comment by Morfey216** [comment]
Я не рекомендую писать конструкцию так
https://github.com/kirillstepanchuk/tehnomart/blob/23f56092d99752d1a10e674740ec57ef9b3c08d6/css/style.css#L194-L197

Или прописывай цвет прямо в свойстве background (что правильно), или пиши уж background-color после составного свойства.

**Comment by kirillstepanchuk** [comment]
сделал

**Comment by Morfey216** [comment]
Все хорошо, за одним моментом: так уж повелось, что в последовательности вначале обычно прописывают цвет, а затем уже ссылку на изображение и другие параметры. Это не ошибка, скорее - некое соглашение.
https://github.com/kirillstepanchuk/tehnomart/blob/c0b6374bda99e6efa968103e0118d0ad62847f88/css/style.css#L223

**Comment by kirillstepanchuk** [comment]
поменял
