### ISSUE TITLE
Заголовок первого уровня

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#4]
По правилам семантики на странице допустим только один заголовок первого уровня - это самый главный заголовок страницы

https://github.com/kirillstepanchuk/tehnomart/blob/a28a5d5a3c627f389d110a08939c6744e8312468/index.html#L113
https://github.com/kirillstepanchuk/tehnomart/blob/a28a5d5a3c627f389d110a08939c6744e8312468/index.html#L140
https://github.com/kirillstepanchuk/tehnomart/blob/a28a5d5a3c627f389d110a08939c6744e8312468/index.html#L152

**Comment by Morfey216** [comment]
Не исправлено:
https://github.com/kirillstepanchuk/tehnomart/blob/4bcb3b7331cc1aeab9a8a1a4c40112f2646b10e1/catalog.html#L74

**Comment by kirillstepanchuk** [comment]
заменил на заголовки других уровней
