### ISSUE TITLE
Активные состояния

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#40]
Для многих элементов не прописаны активные состояния
http://joxi.ru/YmExPRaiJjqY0r

Смотри стайлгайд: http://joxi.ru/E2p4OR1Ta8xDa2

**Comment by kirillstepanchuk** [comment]
ну вроде то,что мог, то прописал, не прописывал тени и я так понимаю там еще с прозрачностью много всякого

**Comment by Morfey216** [comment]
Не всё прописано... Пара скриншотов:
http://joxi.ru/Vm6P8qxTjXdyDA
http://joxi.ru/5mdJPjYCeKVNeA

**Comment by kirillstepanchuk** [comment]
прописал

**Comment by Morfey216** [comment]
Не исправлено
http://joxi.ru/gmv4yJvTvQDvzA
https://gyazo.com/e5a7b940305bab5955a10951952e6546

**Comment by kirillstepanchuk** [comment]
сделал
