### ISSUE TITLE
Единообразие написания стилей

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#43]
Выбери для себя определенный порядок и пиши в едином стиле:
https://github.com/kirillstepanchuk/tehnomart/blob/b20d271306da97ae4ab61325e2df3f5a4bd2c530/css/style.css#L262-L268
https://github.com/kirillstepanchuk/tehnomart/blob/b20d271306da97ae4ab61325e2df3f5a4bd2c530/css/style.css#L275-L280

**Comment by kirillstepanchuk** [comment]
готово
