### ISSUE TITLE
Логотип

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#44]
В данном макете логотип очень простой и шрифт надписи совпадает со шрифтами сайта, поэтому нерентабельно делать его картинкой. Нужно исправить на текстовую версию
https://github.com/kirillstepanchuk/tehnomart/blob/b20d271306da97ae4ab61325e2df3f5a4bd2c530/index.html#L18-L20

**Comment by kirillstepanchuk** [comment]
сделал

**Comment by Morfey216** [comment]
Я изменений не вижу
https://github.com/kirillstepanchuk/tehnomart/blob/b20d271306da97ae4ab61325e2df3f5a4bd2c530/index.html#L18-L20
