### ISSUE TITLE
Дублирование кода

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#45]
Вначале пару примеров:
https://github.com/kirillstepanchuk/tehnomart/blob/c0b6374bda99e6efa968103e0118d0ad62847f88/css/style.css#L312-L319
https://github.com/kirillstepanchuk/tehnomart/blob/c0b6374bda99e6efa968103e0118d0ad62847f88/css/style.css#L383-L390
https://github.com/kirillstepanchuk/tehnomart/blob/c0b6374bda99e6efa968103e0118d0ad62847f88/css/style.css#L416-L423

Такие задачи решаются через указание одного базового класса, внутри которого как раз и прописываются все основные стили. Если у элемента есть какое-то отличие, это отличие описывается во втором, дополнительном классе. Подобный подход позволяет избежать а) дублирования кода, б) рутинной работы в случае будущих исправлений

**Comment by kirillstepanchuk** [comment]
сделано

**Comment by Morfey216** [comment]
Мне кажется, или это всё же один и тот же цвет?
http://joxi.ru/823Pl1xTDXYPnA

**Comment by kirillstepanchuk** [comment]
исправил
