### ISSUE TITLE
Названия классов

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#47]
В названии классов не отражается суть содержимого.
main-nav-content - в этом блоке точно не контент навигации
https://github.com/kirillstepanchuk/tehnomart/blob/5229d2fb15060f06a4b620c64f2f0137abf0ebe6/index.html#L96-L98
https://github.com/kirillstepanchuk/tehnomart/blob/5229d2fb15060f06a4b620c64f2f0137abf0ebe6/index.html#L111

То же самое здесь: Популярные производители - это не popular-product
https://github.com/kirillstepanchuk/tehnomart/blob/5229d2fb15060f06a4b620c64f2f0137abf0ebe6/index.html#L198-L201

**Comment by kirillstepanchuk** [comment]
исправил
