### ISSUE TITLE
Избыточность кода

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#48]
Уверен, можно обойтись меньшим количеством оберток
http://joxi.ru/eAOQPpYSpZOo6m

**Comment by kirillstepanchuk** [comment]
убрал

**Comment by Morfey216** [comment]
У тебя всё еще огромное количество лишних оберток!!!
К примеру - зачем тебе здесь div, если ты его никак не стилизуешь?
http://joxi.ru/8AneRLoF7n3PD2

Я его убираю - что-то изменилось?
http://joxi.ru/Dr85J0yfzyBRjm

**Comment by kirillstepanchuk** [comment]
исправил
