### ISSUE TITLE
Значение высоты

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#49]
Высота текстовых блоков регулируется не через свойство height. 
https://github.com/kirillstepanchuk/tehnomart/blob/5229d2fb15060f06a4b620c64f2f0137abf0ebe6/css/style.css#L114-L125

**Comment by kirillstepanchuk** [comment]
исправил

**Comment by Morfey216** [comment]
Неправильно.
У тебя прописано 
https://github.com/kirillstepanchuk/tehnomart/blob/38fef2cdfd4e15b9fe78d57e5b3c56aa1a9132a6/css/style.css#L138

А должно быть
http://joxi.ru/52a7PqzIbvjz1r

**Comment by kirillstepanchuk** [comment]
заменил
