### ISSUE TITLE
Декоративные изображения

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#5]
Не совсем понял, про что эти ссылки с изображениями внутри...
https://github.com/kirillstepanchuk/tehnomart/blob/a28a5d5a3c627f389d110a08939c6744e8312468/index.html#L62-L72

Если это про эти блоки: http://joxi.ru/J2b8PMVtGMNwKr
то оформляются они не так...
В разметку пойдет только заголовок карточки (скорее всего - третьего уровня) и ссылка.
То есть, будет так:

  ```
<h3>Инструмент</h3>
  <a class="promo-button" href="#">На все случаи</a>
```

Ну и в данном случае да, будет нужна обёртка - либо div, либо элемент списка (если карточки списком делать)

Всё остальное оформляется через стили: и фоновый цвет и картинка-иконка

**Comment by Morfey216** [comment]
Не всё исправлено - эти изображения тоже декоративные
https://github.com/kirillstepanchuk/tehnomart/blob/4bcb3b7331cc1aeab9a8a1a4c40112f2646b10e1/catalog.html#L41-L43

**Comment by kirillstepanchuk** [comment]
картинки заменил на разметку , декоративные изображения сделал ссылками

**Comment by kirillstepanchuk** [comment]
картинки заменил на разметку , декоративные изображения сделал ссылками

**Comment by kirillstepanchuk** [comment]
картинки заменил на разметку , декоративные изображения сделал ссылками

**Comment by Morfey216** [comment]
Ладно, оставим пока этот вопрос до момента стилизации
