### ISSUE TITLE
Центровщик

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#51]
Тут сразу 3 момента:
1. Обычно вначале указывают размер, а уже затем отступы
2. Не указаны внутренние отступы (padding), по макету они по бокам составляют 10px
3. Центровщику обычно задают класс container или wrapper. Это не ошибка, просто так принято

https://github.com/kirillstepanchuk/tehnomart/blob/5229d2fb15060f06a4b620c64f2f0137abf0ebe6/css/style.css#L301-L305

**Comment by kirillstepanchuk** [comment]
исправил

**Comment by Morfey216** [comment]
Какой должна быть (по макету) ширина центровщика? И какая у тебя?
https://github.com/kirillstepanchuk/tehnomart/blob/38fef2cdfd4e15b9fe78d57e5b3c56aa1a9132a6/css/style.css#L315-L321

Пересмотри еще раз блочную модель документа, в частности - размеры
http://htmlbook.ru/blog/shirina-bloka

**Comment by kirillstepanchuk** [comment]
сделал
