### ISSUE TITLE
Критерий Д25

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#52]
https://github.com/kirillstepanchuk/tehnomart/blob/38fef2cdfd4e15b9fe78d57e5b3c56aa1a9132a6/css/style.css#L10-L12

**Comment by kirillstepanchuk** [comment]
изменил

**Comment by Morfey216** [comment]
Это ситуацию не меняет
https://github.com/kirillstepanchuk/tehnomart/blob/f435a2a9fc0358be264dd152cc3ab7a08f5f8891/css/style.css#L10-L12

**Comment by kirillstepanchuk** [comment]
изменил
