### ISSUE TITLE
Параметры шрифта

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#54]
Честно говоря, думал, ты сам заметишь...
http://joxi.ru/KAg46voTX9vvjr
http://joxi.ru/bmo43ZzT9QKKe2

**Comment by kirillstepanchuk** [comment]
я не думал , что в футере лого отличается, исправил

**Comment by Morfey216** [comment]
Хм... А в макете посмотреть не пробовал?..

Тебя ничего не смущает в этом коде?

https://github.com/kirillstepanchuk/tehnomart/blob/cd9fc45d836144e2132c7afd21fcde49e97a1ffb/css/style.css#L125-L144
https://github.com/kirillstepanchuk/tehnomart/blob/cd9fc45d836144e2132c7afd21fcde49e97a1ffb/css/style.css#L752-L771

**Comment by kirillstepanchuk** [comment]
вроде так , если не так , то будет обидно

**Comment by Morfey216** [comment]
Теперь всё правильно ))
