### ISSUE TITLE
Улучшаем код

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#56]
1. В стилях перед открывающей фигурной скобкой ставится пробел
2. Приведи код стилей в единообразный вид
https://github.com/kirillstepanchuk/tehnomart/blob/cd9fc45d836144e2132c7afd21fcde49e97a1ffb/css/style.css#L612-L616
https://github.com/kirillstepanchuk/tehnomart/blob/cd9fc45d836144e2132c7afd21fcde49e97a1ffb/css/style.css#L639-L645
https://github.com/kirillstepanchuk/tehnomart/blob/cd9fc45d836144e2132c7afd21fcde49e97a1ffb/css/style.css#L773-L780
3. line-height рекомендую писать сразу после font-size
https://github.com/kirillstepanchuk/tehnomart/blob/cd9fc45d836144e2132c7afd21fcde49e97a1ffb/css/style.css#L752-L763

**Comment by kirillstepanchuk** [comment]
сделал

**Comment by Morfey216** [comment]
Ну ты уж определись в конце концов с последовательностью кода, что в каком порядке у тебя будет идти. А то в одном фрагменте идут сначала списочные параметры, а затем размерности, а в другом - наоборот

https://github.com/kirillstepanchuk/tehnomart/blob/6f63c914b7a9e2785419ce1cb56eebd67456bc1f/css/style.css#L408-L414
https://github.com/kirillstepanchuk/tehnomart/blob/6f63c914b7a9e2785419ce1cb56eebd67456bc1f/css/style.css#L437-L441

**Comment by kirillstepanchuk** [comment]
пропустил случайно, исправил
