### ISSUE TITLE
Нарушение ТЗ интерфейса залогиненного пользователя

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#57]
Реализация не соответствует ТЗ:
3.4. В блоке авторизованного посетителя имя и иконка пользователя являются
ссылкой на профайл, а иконка выхода — на страницу деавторизации.

Другими словами, объединены разные элементы интерфейса: https://gyazo.com/0f256ef93bb9cd1b04eb0f2aa7579c71

Должно быть так: https://gyazo.com/ea58a76e9c0faf563785d54fd98df8d5

**Comment by kirillstepanchuk** [comment]
исправил
