### ISSUE TITLE
Обертки

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#59]
Уверен, от большинства оберток можно избавиться
https://github.com/kirillstepanchuk/tehnomart/blob/75925175d87f9129b57c1f9546f79ec2c2ab2768/index.html#L14-L39

**Comment by kirillstepanchuk** [comment]
убрал

**Comment by Morfey216** [comment]
Можно лучше...
И не только в этом фрагменте кода

**Comment by kirillstepanchuk** [comment]
убрал несколько оберток

**Comment by Morfey216** [comment]
Можно лучше!!!
Пример: http://joxi.ru/Dr85J0yfzWjlDm

Это твой код, из которого я выбросил некоторые ненужные div-ы...

Или эта обертка - зачем она? У тебя для нее даже стилей нет!!!
https://github.com/kirillstepanchuk/tehnomart/blob/94112fe385b21f74e3164925d5eacd61248878b5/index.html#L52

**Comment by kirillstepanchuk** [comment]
уверен конечно , что не все , но старался максимально убрать
