### ISSUE TITLE
Карточки товаров

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#60]
Различаются позиции кнопки с ценой:
http://joxi.ru/bmo43ZzT90GVp2

**Comment by kirillstepanchuk** [comment]
сделал

**Comment by Morfey216** [comment]
Данное решение не оптимально! Давай сравним фрагменты кода:
https://github.com/kirillstepanchuk/tehnomart/blob/a9ce44dd3ba59fa7ea4f7ff4771a7e0afcae5906/index.html#L226-L227
и
https://github.com/kirillstepanchuk/tehnomart/blob/a9ce44dd3ba59fa7ea4f7ff4771a7e0afcae5906/index.html#L214-L216
Слишком много отличий, чтобы просто убрать или добавить дисконт. 
На практике очень нерационально

**Comment by kirillstepanchuk** [comment]
сделал

**Comment by Morfey216** [comment]
почему не удален избыточный класс у заголовка?
https://github.com/kirillstepanchuk/tehnomart/blob/94112fe385b21f74e3164925d5eacd61248878b5/catalog.html#L275-L276

**Comment by kirillstepanchuk** [comment]
убрал
