### ISSUE TITLE
Элементы управления слайдами

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#63]
Элементы управления должны быть на слайдере, а не на слайдах
http://joxi.ru/KAx48GoT1L93aA

Другими словами, они должны быть в единственном числе

**Comment by kirillstepanchuk** [comment]
исправил

**Comment by Morfey216** [comment]
Полная каша в разметке! Исправить!
https://github.com/kirillstepanchuk/tehnomart/blob/a9ce44dd3ba59fa7ea4f7ff4771a7e0afcae5906/index.html#L121-L162

**Comment by kirillstepanchuk** [comment]
исправил

**Comment by Morfey216** [comment]
Ну вот - гораздо лучше, почти идеально ))
Я бы еще убрал общую обёртку с кнопок навигации и пагинации, ну нет в ней смысла и пользы
https://github.com/kirillstepanchuk/tehnomart/blob/94112fe385b21f74e3164925d5eacd61248878b5/index.html#L118-L142

**Comment by kirillstepanchuk** [comment]
убрал
