### ISSUE TITLE
Форма поиска

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#65]
Основная претензия - к именованию классов
https://github.com/kirillstepanchuk/tehnomart/blob/94112fe385b21f74e3164925d5eacd61248878b5/index.html#L21-L28

Вопрос: какую задачу выполняет форма с классом class="header-form" ? Это форма заголовка? Или главная форма? Что это?

**Comment by kirillstepanchuk** [comment]
переделал
