### ISSUE TITLE
Иерархия заголовков

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#67]
По всем признакам - здесь должны быть H3
https://github.com/kirillstepanchuk/tehnomart/blob/94112fe385b21f74e3164925d5eacd61248878b5/catalog.html#L125
https://github.com/kirillstepanchuk/tehnomart/blob/94112fe385b21f74e3164925d5eacd61248878b5/catalog.html#L217

**Comment by kirillstepanchuk** [comment]
переделал
