### ISSUE TITLE
Нарушение вёрстки

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#69]
При изменении контента вёрстка ломаться не должна!
Я изменил всего лишь одно слово, причем в пределах логики - и вот результат:
http://joxi.ru/EA4Py7zTONj55A

Уверен, что это связано с данной ошибкой https://github.com/kirillstepanchuk/tehnomart/issues/68#issue-602247744

**Comment by kirillstepanchuk** [comment]
сделал
