### ISSUE TITLE
Несоответствие ТЗ

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#7]
https://github.com/kirillstepanchuk/tehnomart/blob/a28a5d5a3c627f389d110a08939c6744e8312468/index.html#L93-L106

По ТЗ:
3.9. Блок «Популярные производители»: карточка производителя является ссылкой

**Comment by Morfey216** [comment]
Всё еще не все элементы размечены:
http://joxi.ru/LmG1PXeIJZ7J3A

**Comment by Morfey216** [comment]
Как ты думаешь - эти вещи в разметке на главной должны присутствовать?
https://github.com/kirillstepanchuk/tehnomart/blob/4bcb3b7331cc1aeab9a8a1a4c40112f2646b10e1/catalog.html#L39-L49

**Comment by kirillstepanchuk** [comment]
элементы разметил, популярные производители как ссылка, теперь и главная и каталог от лица авторизированного пользователя

**Comment by Morfey216** [comment]
Теперь не наблюдаю разметки следующих элементов:
http://joxi.ru/eAOQPpYSpERjBm

**Comment by kirillstepanchuk** [comment]
добавил за блоком авторизированного пользователя блок неавторизированного

**Comment by Morfey216** [comment]
Описал ошибку здесь: https://github.com/kirillstepanchuk/tehnomart/issues/18#issue-571647890
