### ISSUE TITLE
Проценты

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#70]
Я насчитал что-то около 10-тка подобных вещей
https://github.com/kirillstepanchuk/tehnomart/blob/94112fe385b21f74e3164925d5eacd61248878b5/css/style.css#L873
https://github.com/kirillstepanchuk/tehnomart/blob/94112fe385b21f74e3164925d5eacd61248878b5/css/style.css#L1789

**Comment by kirillstepanchuk** [comment]
да , подзабыл чутка, убрал
