### ISSUE TITLE
Атрибуты тегов

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/tehnomart#8]
https://github.com/kirillstepanchuk/tehnomart/blob/a28a5d5a3c627f389d110a08939c6744e8312468/index.html#L98-L105

В разметке у всех изображений необходимо будет прописать размер и alt. Размеры можешь указать позже (на следующем этапе), а alt пропиши сейчас

**Comment by Morfey216** [comment]
Совершенно не информативно...
https://github.com/kirillstepanchuk/tehnomart/blob/4bcb3b7331cc1aeab9a8a1a4c40112f2646b10e1/index.html#L14

Если изображение по каким-то причинам не подгрузится, на его месте будет эта надпись - что из нее поймет пользователь?

**Comment by kirillstepanchuk** [comment]
Заголовок поменял на Tehnomart , к картинкам добавил названия изображенных на них компаний

**Comment by Morfey216** [comment]
Не исправлено!
Один случай из многих:
https://github.com/kirillstepanchuk/tehnomart/blob/67a896fd2857159afd7c51618443998daf501d0c/catalog.html#L130

**Comment by kirillstepanchuk** [comment]
альты везде поставил
